import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { SOCIAL } from "@/lib/social";

const src = readFileSync("src/components/social/social-go-live.tsx", "utf8");
const page = readFileSync("src/app/(app)/social/live/page.tsx", "utf8");
const loading = readFileSync("src/app/(app)/social/live/loading.tsx", "utf8");
const fan = readFileSync("src/components/social/social-create-fan.tsx", "utf8");
const sheet = readFileSync("src/components/social/social-create-sheet.tsx", "utf8");

describe("Social Go live recorder", () => {
  it("records in-app then posts on the normal video path with a 10:00 cap", () => {
    expect(page).toContain("SocialGoLive");
    expect(page).toContain("data-social-go-live-page");
    expect(src).toContain("data-social-go-live");
    expect(src).toContain("data-social-go-live-timer");
    expect(src).toContain("MediaRecorder");
    expect(src).toContain("persistSocialPost");
    expect(src).toContain("runSocialOptimisticMutation");
    expect(src).toContain("uploadSocialPostMedia");
    expect(src).toContain('intent: "live"');
    expect(src).toContain("goLiveReachedCap");
    expect(src).toContain("goLiveFitsByteCap(used + event.data.size");
    expect(src).toContain("new MediaRecorder(stream, { mimeType: probed.raw })");
    expect(src).toContain("aliveRef");
    expect(src).toContain("attachPromiseRef");
    expect(src).toContain("ensurePreview");
    expect((src.match(/liveRef\.current = nextStoryStudioLive/g) ?? []).length).toBe(1);
    expect(src).toContain("releaseCamera");
    expect(src).not.toContain("await createSocialPost");
    expect(src).not.toMatch(/persistSocialPost\(started.form\);[\s\S]{0,120}catch/);
    expect(src).toContain("SOCIAL_GO_LIVE_MAX_MS");
    expect(src).toContain("HouseVoiceMic");
    expect(src).toContain('surface="dictate"');
    expect(src).not.toContain("LiveStream");
    expect(src).not.toContain("IVS");
    expect(src).not.toContain("WebRTC");
    expect(src).not.toContain("liveHint");
    expect(src).not.toContain("Record up to 10 minutes");
    expect("liveHint" in SOCIAL.create).toBe(false);
    expect(src).toContain("SOCIAL.create.goLive");
    expect(src).toContain("SOCIAL.stories.flipCamera");
    expect(src).toContain("data-social-go-live-record");
    expect(src).toContain("data-social-go-live-close");
    expect(src).toContain("takeSocialGoLiveExitHref()");
    expect(src).toContain("router.replace(takeSocialGoLiveExitHref())");
    expect(src).toContain("clearSocialGoLiveOpener()");
    expect(src).not.toContain("href={SOCIAL_ROUTES.create}");
    expect(src).not.toContain('href="/social/create"');
    expect(loading).toContain("data-house-rsc-fallback");
    expect(loading).toContain("data-social-go-live-page");
    expect(loading).not.toContain("SocialCreateSkeleton");
    expect(loading).not.toContain("Share something");
    expect(fan).toContain("rememberSocialGoLiveOpener");
    expect(sheet).toContain("rememberSocialGoLiveOpener");
    const fanMedia = fan.slice(fan.indexOf('tile.id === "media"'), fan.indexOf('tile.id === "live"'));
    expect(fanMedia).toContain("openPicker()");
    expect(fanMedia).not.toContain("rememberSocialGoLiveOpener");
    const fanLive = fan.slice(fan.indexOf('if (tile.id === "live")'));
    expect(fanLive.indexOf("rememberSocialGoLiveOpener")).toBeGreaterThan(-1);
    expect(fanLive.indexOf("rememberSocialGoLiveOpener")).toBeLessThan(fanLive.indexOf("closeFan()"));
  });
});
